exports.zones = [
  'ARGENTARIO',
  'BONDONE E SARDAGNA',
  'CRISTO RE - SAN MARTINO',
  'GARDOLO',
  'GARDOLO ZONA INDUSTRIALE - MEANO',
  'MATTARELLO',
  'OLTREFERSINA',
  'PIEDICASTELLO - SOLTERI - VELA - CAMPOTRENTINO',
  'POVO - VILLAZZANO',
  'RAVINA - ROMAGNANO',
  'S. GIUSEPPE - S. CHIARA',
  'VIA KOFLER - CASTELLER'
]
